### ISSUE TITLE
notmuch2 bindings package

### ISSUE THREAD

**Issue by lenormf** [weilbith/notmuch-python-bindings#1]
Hi,

The developers of NotMuch are going to deprecate the regular bindings,
and have them replaced with CFFI-based `notmuch2` bindings.

They've pushed a Debian package[1], stating that:

>This patch encourages new downstream development to rely on notmuch2
>instead of on notmuch, to get the benefits of the new module.

Could you please create a `notmuch2` bindings package for PyPi? The
Alot[2] MUA is going to start using them soon-ish, your help would be
greatly appreciated.

Thanks!

[1] https://www.mail-archive.com/notmuch@notmuchmail.org/msg48850.html
[2] https://github.com/pazz/alot

**Comment by weilbith** [comment]
I filed [an issue](https://foss.heptapod.net/pypy/cffi/issues/455) how I can define the `cffi` build script for _Poetry_. Their documentation only states that you can use `setuptools` and define there the property `cffi_modules`. Hope I get help there. But maybe you also know the answer?

**Comment by lenormf** [comment]
No idea, sorry!

**Comment by lenormf** [comment]
The NotMuch2 bindings are available in a [RC2](https://git.notmuchmail.org/git?p=notmuch;a=commitdiff;h=af51e67127e5817e3795973da9c5e2148b7fdeec) now, won't be long until v0.30 is out.

Could you please get something going, even without Poetry support?

**Comment by weilbith** [comment]
Sure I could do a new repo and simply use their project setup. But this would then be a new package with a new name. If you feel better me doing this then okay. I can try to schedule this today night after work. 
What would be the most easy approach to test this package then? Any suggestions?

**Comment by lenormf** [comment]
That would be great!

I've already created a package for ArchLinux, and it felt like the best move to ask you if you could create another Pypi package. Here is the file, for reference:

```sh
pkgname=python-notmuch2
pkgver=0.30_rc2_1
pkgrel=1
pkgdesc="CFFI Python bindings for the NotMuch email program"
arch=("x86_64")
url="https://notmuchmail.org/"
license=("GPL3")
depends=("notmuch-runtime>=0.29.3")
makedepends=("python" "python-sphinx")
makedepends=("python")
source=("${pkgname}::git+https://gitlab.com/dkg/notmuch.git#branch=master"
)
sha256sums=("SKIP"
)

pkgver() {
    cd "${srcdir}/${pkgname}"
    git describe --tags | sed -E 's,.+/,,; s,-,_,g'
}

prepare() {
    cd "${srcdir}/${pkgname}"
}

build() {
    cd "${srcdir}/${pkgbase}/bindings/python-cffi"

    python setup.py build
}

check() {
    cd "${srcdir}/${pkgbase}/bindings/python-cffi"

    python setup.py test
}

package(){
    cd "${srcdir}/${pkgbase}/bindings/python-cffi"

    python setup.py install --root="${pkgdir}"
}
```

The package name is `python-notmuch2` because the developers have submitted a Debian package called `python3-notmuch2`, so a possible/logical package name for Pypi could be `notmuch2`?

The `bindings/python-cffi` directory in the upstream code comes with a test suite, and it can easily be run with `setup.py test`.

Thanks!

**Comment by weilbith** [comment]
Here we go. Please check it out at [PyPI](https://pypi.org/project/notmuch2/). Will close this after getting some positive feedback by you.

**Comment by lenormf** [comment]
Fantastic! I'll check it out and close the issue if no further actions are needed. Thanks!

**Comment by lenormf** [comment]
It's looking good.

Any chance you could use the same version number for the package as the upstream releases? It'd make more sense to have `notmuch2>=0.30` in my manifest, rather than `0.1`. It can wait until v0.30 is official out, though.

**Comment by weilbith** [comment]
Hmm. The bindings actually have their own version. So I just took the original version number from [here](https://git.notmuchmail.org/git?p=notmuch;a=blob;f=bindings/python-cffi/setup.py;h=37918e3d2cdb3b7bcf0a3e3db860bfab5bd1b0db;hb=HEAD). I did not plan to introduce my own versioning. It should be basically a mirror of the upstream, including the version number.:

**Comment by lenormf** [comment]
I asked the developers about that on [their mailing list](https://notmuchmail.org/pipermail/notmuch/2020/029671.html). I wouldn't expect the bindings to have a different version number, we'll see what they say.

cc @flub

**Comment by weilbith** [comment]
Okay. If they change it I'm totally fine with it. I mean than they will update their version number which causes me to update as well. ^^
So if the package works and it is only about the version number, could we maybe close the issue for now and you open another one if you get a response?

**Comment by lenormf** [comment]
I got a partial response from the benevolent dictator of the project, it looks likely that the version number of the bindings will follow that of the rest of the code.

Closing in the meantime, I'll PING you when they actually change the code to reflect that.

Thanks again!

**Comment by lenormf** [comment]
The patch is in, the version is now officially `0.30~rc2`.

**Comment by weilbith** [comment]
It is now available as [pre-release](https://pypi.org/project/notmuch2/#history) at PyPI.
